### ISSUE TITLE
Improve the Debug App

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#267]
## Description
The current implementation of the Debug App includes several areas for improvement. Specifically, we need to:

- Add functionality to output the array of Point Cloud data and any edits made to it in the Picking App
- Add support for touch events
- Update the way we load ES modules
- Add the ability to handle key and mouse events

## Tasks
 - [x] Add output functionality for Point Cloud data and edits
 - [ ] Add touch event support
 - [x] Update the way we load ES modules
 - [x] Add key and mouse event handling functionality

## Additional Information
This improvement to the Debug App will help to make it more useful and efficient for developers working on the project.
