### ISSUE TITLE
0.7.1 release checklist

### ISSUE THREAD

**Issue by daisuke201** [sony/mapray-js#64]
- [x] Update samples and sample list
- [x] Update change lists
- [x] Update README

**Comment by daisuke201** [comment]
- [ ] update path of mapray.js from v0.7.0 to v0.7.1

**Comment by daisuke201** [comment]
- [ ] Add UI Engine

**Comment by daisuke201** [comment]
Released v0.7.1
